a= int(input("Enter the value:-"))
b= int(input("Enter the value:-"))
print(a+b)
a= float(input("Enter the value:-"))
b= float(input("Enter the value:-"))
print(a+b)
a= eval(input("Enter the value:-"))
b= eval(input("Enter the value:-"))
print(a+b)